name: flutter_assignment
description: "Flutter assignment project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: 4.6.5
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.3
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  intl:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

#  fonts:
#    - family: inter
#      fonts:
#        - asset: assets/font/Inter-Bold.ttf
#          weight: 700
#        - asset: assets/font/Inter-SemiBold.ttf
#          weight: 600
#        - asset: assets/font/Inter-Medium.ttf
#          weight: 500
#        - asset: assets/font/Inter-Regular.ttf
#          weight: 400